apiVersion: apps/v1
kind: Deployment
metadata:
  name: spammer-leader
  labels:
    app: spammer
    type: leader
spec:
  selector:
    matchLabels:
      app: spammer
      type: leader
  template:
    metadata:
      labels:
        app: spammer
        type: leader
    spec:
      containers:
      - name: spammer
        image: leonpatmore/spammer-v2:b725316ad0c71493d2b636519476f168dc0d88c1
        ports:
        - containerPort: 8080
        env:
        - name: SPAMMER_PORT
          value: "8080"
        - name: SPAMMER_TYPE
          value: leader
      - name: ui
        image: leonpatmore/spammer-v2-ui:7120557cf6df7ce6da1034bf8138534dd3aa3e73
        ports:
        - containerPort: 3000
        env:
        - name: SPAMMER_LEADER_HOST
          value: "localhost"
        - name: SPAMMER_LEADER_PORT
          value: "8080"
