apiVersion: apps/v1
kind: Deployment
metadata:
  name: spammer-leader
  labels:
    app: spammer
    type: leader
spec:
  selector:
    matchLabels:
      app: spammer
      type: leader
  template:
    metadata:
      labels:
        app: spammer
        type: leader
    spec:
      containers:
      - name: spammer
        image: leonpatmore/spammer-v2:f5d1341e07ea58be50041d69a5e63ce3bfbb52ed
        ports:
        - containerPort: 8080
        env:
        - name: SPAMMER_PORT
          value: "8080"
        - name: SPAMMER_TYPE
          value: leader
      - name: ui
        image: leonpatmore/spammer-v2-ui:b005cea2647c39b67e5492562e4d96a49a1f79ae
        ports:
        - containerPort: 3000
        env:
        - name: SPAMMER_API_PORT
          value: "8080"
