kind: Service
apiVersion: v1
metadata:
  name: spammer-leader
spec:
  type: LoadBalancer
  selector:
    app: spammer
    type: leader
  ports:
    - name: ui
      port: 80
      targetPort: 80
    - name: api
      port: 8080
      targetPort: 8080
