apiVersion: apps/v1
kind: Deployment
metadata:
  name: spammer-follower
  labels:
    app: spammer
    type: follower
spec:
  replicas: {{ .Values.followerReplicas }}
  selector:
    matchLabels:
      app: spammer
      type: follower
  template:
    metadata:
      labels:
        app: spammer
        type: follower
    spec:
      containers:
      - name: spammer
        image: leonpatmore/spammer-v2:f5d1341e07ea58be50041d69a5e63ce3bfbb52ed
        ports:
        - containerPort: 8080
        env:
        - name: SPAMMER_PORT
          value: "8080"
        - name: SPAMMER_TYPE
          value: follower
        - name: SPAMMER_INITIAL_LEADER_SOCKET_ADDRESS
          value: "spammer-leader:8080"
